name: Docker Image CI

on:
  push:
    tags:
        - '*'
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)    
      - name: Extract tag from manual input
        run: echo "TAG=${{github.event.inputs.tag}}" >> $GITHUB_ENV
        if: github.event_name == 'workflow_dispatch'
      
      - name: Extract tag from push
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        if: github.event_name == 'push'
      
      - name: Determine release or dev
        run: |
          if echo "${{env.TAG}}" | grep -q "release"; then
            echo "TAG=release" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
          fi

      - name: Login
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push:
            true
          tags: 
            ghcr.io/michaeljberk/other-rda-aps:${{env.TAG}}
